version: "3.8"
services:
    db: # Connect to service using: psql -U postgres safeackdb -h localhost
        image: postgres:16
        networks:
            - safeack
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
            - POSTGRES_DB=${POSTGRES_DB:-safeackdb}
        volumes:
            - ./db-data:/var/lib/postgresql/data

    # backend:
    #     image: safeack/safeack-backend:latest
    #     ports:
    #         - "8000:8000"
    #     networks:
    #         - safeack
    #     depends_on:
    #         - db
    #     environment:
    #         SQLALCHEMY_DATABASE_URL: sqlite:///./sql_app.db # TODO: change to postgresql from sqlite
    #     env_file:
    #         - ./docker.env
    #     volumes:
    #         - ./gunicorn-logs:/var/log/gunicorn

networks:
    safeack:

volumes:
    db-data:
