"""add role in users table

Revision ID: 5f92d8b744a6
Revises: 1ba4c36d2ca3
Create Date: 2024-02-06 00:37:17.107206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f92d8b744a6'
down_revision: Union[str, None] = '1ba4c36d2ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('role', sa.Enum('USER', 'STAFF', 'SUPERUSER', name='role'), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
